.TH JACK.PLAY "1" 0.4 "November 2006"
.SH NAME
jack.play \- JACK Sound File Player
.SH SYNOPSIS
.BR jack.play
.RI [ options ]
.I sound-file...
.SH OPTIONS
.TP
.B \-b
Set the disk buffer size in frames (default=4096).  This value must be
a power of two.  If the JACK period size at any time exceeds this
value the player will halt.
.TP
.B \-c
Set the sample rate conversion algorithm (default=2).  Values are:
SRC_SINC_BEST_QUALITY = 0, SRC_SINC_MEDIUM_QUALITY = 1,
SRC_SINC_FASTEST = 2, SRC_ZERO_ORDER_HOLD = 3 and SRC_LINEAR = 4.
.TP
.B \-i
Set the initial disk seek in frames (default=0).
.TP
.B \-m
Set the minimal disk transfer size in frames (default=32). This is an
optimization switch.
.TP
.B \-n
Set the client name (default=jack.play).
.TP
.B \-q
Set the frame size to request data from the ringbuffer (default=64). This is an
optimization switch.
.TP
.B \-r
Set the resampling ratio multiplier (default=1.0).
.TP
.B \-t
Run in JACK transport aware mode.
.TP
.B \-u
Do not make client name unique by appending process identifier.
.SH DESCRIPTION
.B jack.play
is a light-weight 
.B JACK
sound file player. It creates as many output ports as there are
channels in the input file.  It implements no connection logic, use
.BR jack.plumbing (1)
instead.
.PP
.B jack.play 
will read files in any format supported by
.BR libsndfile ,
and will resample to match the server sample rate using
.BR libsamplerate .
.SH AUTHOR
Rohan Drape <http://slavepianos.org/rd/>
.SH SEE ALSO
.BR jackd "(1), " libsndfile "(3) <http://mega-nerd.com/libsndfile/>, " 
.BR libsamplerate "(3) <http://mega-nerd.com/SRC/>"
