.TH JACK.SCOPE "1" 0.1 "February 2006"
.SH NAME
jack.scope \- JACK Oscilloscope
.SH SYNOPSIS
.B jack.scope 
.RI [ options ]
.SH OPTIONS
.TP
.B \-b
Set the frame size of the data displayed by the scope (default=512).
.TP
.B \-d
Set the delay interval in milli-seconds between scope updates
(default=100.0).
.TP
.B \-f
Request that a still image file of each frame be stored to the
indicated directory.
.TP
.B \-m
Set the scope operating mode (default=signal).  The operating modes
are: 
.IR signal " and " embed.
.TP
.B \-n
Set the number of channels, and therefore the number of JACK input
ports (default=1).  Multiple channels are superimposed, each channel
is drawn in a distinct color.  There is a compile time channel limit.
.TP
.B \-p
Set the port number to listen for OSC packets on (default=57140).
.TP
.B \-w
Set the scope size in pixels (default=512).  The scope window is
square.
.SH DESCRIPTION
.B jack.scope 
is an oscilloscope for 
.B JACK 
under 
.B X11.  
jack.scope draws either a time domain signal trace or a self
correlation trace.  Multiple input channels are superimposed, each
channel is drawn in a different color.  jack.scope accepts 
.B OSC 
packets for interactive control of drawing parameters.
.PP
The operating mode of jack.scope is set using
.BR -m .
In
.I signal
mode jack.scope draws a time domain signal trace, in
.I embed
mode jack.scope draws a self correlation trace.  
.PP
The size of the jack.scope window is set using 
.BR -w , 
the scope window is square.  The window is of fixed size and has
centered gravity.  The time interval that is displayed is determined
by the frame size, set using
.BR -b .  
The image refresh rate is determined by the delay interval, set using
.BR -d .
Note that the interval is truncated to the nearest frame boundary and
that the time taken to compose the image and blit to the screen is
indeterminate.
.PP
The number of JACK input ports that jack.scope creates and monitors is
set using
.BR -n .  
Multiple channels are drawn in superimposition, each channel is drawn
in a distinct color.
.PP
In 
.I signal
mode the trace is drawn in a style set using
.BR /style .
In
.IR dot
mode only the sample pixel in each column is drawn.  In
.I fill 
mode all pixels between the sample pixel and the zero pixel of each
column are drawn.  In
.I line 
mode all pixels between the adjacent sample pixels of each column are
drawn.
.PP
In 
.I embed
mode the trace is a self correlation signal with a sample delay set
using
.BR /embed .  
The delayed sample is on the x-axis.  The interpolation increment is
set using
.BR /incr , 
increment values less than one result in increasingly continuous trace
paths.
.PP
jack.scope can store the animation as a sequence of uncompressed
.BR ppm (5) 
image files.  To request this use the
.B -f
option with the directory files should be written to as the argument.
.PP
The OSC messages understood by jack.scope are given in the table
below.  Each command requires one argument of the indicated type.  The
last column gives the option that sets the same parameter.
.IP
.TS
;
lb l li l .
/mode	drawing-mode	<string>	\-m
/style	style	<string>	N/A
/frames	frame-size	<integer>	\-b
/delay	refresh-interval	<float>	\-d
/embed	embedding	<integer>	N/A
/incr	increment	<float>	N/A
.TE
.PP
jack.scope implements no connection logic, use
.BR jack.plumbing (1)
instead.
.SH REFERENCES
Monro, G. and Pressing, J.  ``Sound Visualization Using Embedding: The
Art and Science of Auditory Autocorrelation'' CMJ, 22/2, 1998.
.SH AUTHOR
Rohan Drape <http://www.slavepianos.org/rd/>.
.SH SEE ALSO
.BR jackd "(1), " X "(7x), " OSC "(7) "
<http://cnmat.berkeley.edu/OSC/>
