.TH JACK.DL "1" 0.5 "October 2008"
.SH NAME
jack.dl \- JACK shared library dsp loader
.SH SYNOPSIS
.B jack.dl
.RI [ options ]
.SH OPTIONS
.TP
.B \-nc
Set the number of input and output channels (default=8).
.TP
.B \-ng
Set the number of graph slots (default=8).
.TP
.B \-nk
Set the number of control buses (default=64).
.TP
.B \-p
Set the udp port number (default=57190).
.SH DESCRIPTION
.B jack.dl
loads dsp algorithms from shared libraries.  Commands are sent as
.B OSC 
packets over a 
.B UDP 
connection.  jack.dl allows data flow code generators to be used 
as interactively.  
.PP
Clients load dsp graphs by sending a "graph load" packet:
.TP
.BI /g_load " index object-file"
.PP
where 
.I index 
is an integer and 
.I object-file
a file name.
.PP
jack.dl implements only a subset of the OSC protocol.  In
particular it does not implement the patten matching rules and does
not implement a scheduler for incoming messages.
.PP
jack.dl drops all unrecognized incoming packets.
.SH AUTHOR
Rohan Drape <http://slavepianos.org/rd/>
.SH SEE ALSO
.BR jackd "(1), " "OSC" "(7) <http://opensoundcontrol.org/>"
