.TH JACK.UDP "1" 0.2 "November 2005"
.SH NAME
jack.udp \- JACK UDP Transport Client
.SH SYNOPSIS
.B jack.udp
.RI [ options ] 
.IR send | recv
.SH OPTIONS
.TP
.B \-b
Set the ring buffer size in frames (default=4096).
.TP
.B \-c
Set the client name (default=jack.udp-PID).
.TP
.B \-n
Set the number of channels, and therefore the number of JACK ports
(default=2).
.TP
.B \-p
Set the port number (default=57160).
.TP
.B \-r
The remote host name, for use in send mode (default="127.0.0.1").
.SH DESCRIPTION
.B jack.udp 
is a UDP audio transport mechansim for
.BR JACK .  
The
.B send
mode reads signals from a set of JACK input ports and sends UDP
packets to the indicated port at the indicated host at a rate
determined by the local JACK daemon.  The
.B recv 
mode reads incoming packets at the indicated port and writes the
incoming data to a set of JACK output ports at a rate that is
determined by the local JACK daemon.
.PP
This transport mechanism is unreliable.  Both send and recv clients
will report buffer overflow and underflow occurences, and recv clients
will report dropped and out-of-order packets, and shutdown on channel
mismatch packets.  In practice this mechanism can be made highly
reliable over local networks.
.PP
jack.udp implements no connection logic, use 
.BR jack.plumbing (1)
instead.
.SH EXAMPLE
192.0.0.1:~$ jack.udp -r 192.0.0.2 send
.br
192.0.0.2:~$ jack.udp recv
.SH AUTHOR
Rohan Drape <http://slavepianos.org/rd/>
.SH SEE ALSO
.BR jackd (1)
